version: "3"
services:
    # Mysql database container
    db:
        image: mysql
        container_name: db_money_conversion
        restart: always
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        networks:
            - conversion

    # phpmyadmin container
    # phpmyadmin:
    #     image: phpmyadmin
    #     container_name: money_conversion
    #     restart: always
    #     depends_on:
    #         - db
    #     ports:
    #         - 8080:80
    #     environment:
    #         PMA_HOST: db
    #     networks:
    #         - conversion

    # Symfony apache project container
    www:
        build: .
        container_name: money_conversion
        ports:
          - "8080:80"
        volumes:
            - ./docker/vhosts:/etc/apache2/sites-enabled
            - ./:/var/www
        restart: always
        networks:
            - conversion

networks:
    conversion:

volumes:
    db-data: